"""initial schema: network hierarchy, associations, synthetic ground truth

Revision ID: 7dc7a3f828e8
Revises: 
Create Date: 2026-09-13 18:57:05.552066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7dc7a3f828e8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connection',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('customer_id', sa.String(length=64), nullable=False),
    sa.Column('meter_id', sa.String(length=64), nullable=False),
    sa.Column('archetype', sa.String(length=32), nullable=False),
    sa.Column('tariff_band', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meter_id')
    )
    op.create_table('network_node',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('node_type', sa.String(length=32), nullable=False),
    sa.Column('parent_id', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('attributes', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['network_node.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_network_node_parent', 'network_node', ['parent_id'], unique=False)
    op.create_table('synthetic_scenario',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('generator_version', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('connection_association',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('connection_id', sa.String(length=64), nullable=False),
    sa.Column('network_node_id', sa.String(length=64), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name='ck_confidence_range'),
    sa.ForeignKeyConstraint(['connection_id'], ['connection.id'], ),
    sa.ForeignKeyConstraint(['network_node_id'], ['network_node.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_assoc_connection', 'connection_association', ['connection_id'], unique=False)
    op.create_index('ix_assoc_node', 'connection_association', ['network_node_id'], unique=False)
    op.create_index('uq_assoc_current_per_connection', 'connection_association', ['connection_id'], unique=True, sqlite_where=sa.text('effective_to IS NULL'), postgresql_where=sa.text('effective_to IS NULL'))
    op.create_table('ground_truth_anomaly',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scenario_id', sa.String(length=64), nullable=False),
    sa.Column('connection_id', sa.String(length=64), nullable=False),
    sa.Column('anomaly_type', sa.String(length=32), nullable=False),
    sa.Column('start_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_ts', sa.DateTime(timezone=True), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['connection.id'], ),
    sa.ForeignKeyConstraint(['scenario_id'], ['synthetic_scenario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_gta_scenario_connection', 'ground_truth_anomaly', ['scenario_id', 'connection_id'], unique=False)
    op.create_table('ground_truth_consumption',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scenario_id', sa.String(length=64), nullable=False),
    sa.Column('connection_id', sa.String(length=64), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('kw', sa.Float(), nullable=False),
    sa.Column('metered_kw', sa.Float(), nullable=False),
    sa.Column('shed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['connection.id'], ),
    sa.ForeignKeyConstraint(['scenario_id'], ['synthetic_scenario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_gtc_scenario_connection_ts', 'ground_truth_consumption', ['scenario_id', 'connection_id', 'ts'], unique=False)
    op.create_table('ground_truth_technical_loss',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scenario_id', sa.String(length=64), nullable=False),
    sa.Column('network_node_id', sa.String(length=64), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('loss_kw', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['network_node_id'], ['network_node.id'], ),
    sa.ForeignKeyConstraint(['scenario_id'], ['synthetic_scenario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_gttl_scenario_node_ts', 'ground_truth_technical_loss', ['scenario_id', 'network_node_id', 'ts'], unique=False)
    op.create_table('sensor_reading',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=False),
    sa.Column('network_node_id', sa.String(length=64), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('measurement', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['network_node_id'], ['network_node.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sensor_node_ts', 'sensor_reading', ['network_node_id', 'ts'], unique=False)
    op.create_table('vending_event',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('connection_id', sa.String(length=64), nullable=False),
    sa.Column('scenario_id', sa.String(length=64), nullable=True),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('kwh_purchased', sa.Float(), nullable=False),
    sa.Column('tariff_band', sa.String(length=32), nullable=False),
    sa.Column('vending_channel', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['connection.id'], ),
    sa.ForeignKeyConstraint(['scenario_id'], ['synthetic_scenario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_vending_connection_ts', 'vending_event', ['connection_id', 'ts'], unique=False)
    op.create_index('ix_vending_scenario', 'vending_event', ['scenario_id'], unique=False)
    # ### end Alembic commands ###
    _promote_hypertables()


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_vending_scenario', table_name='vending_event')
    op.drop_index('ix_vending_connection_ts', table_name='vending_event')
    op.drop_table('vending_event')
    op.drop_index('ix_sensor_node_ts', table_name='sensor_reading')
    op.drop_table('sensor_reading')
    op.drop_index('ix_gttl_scenario_node_ts', table_name='ground_truth_technical_loss')
    op.drop_table('ground_truth_technical_loss')
    op.drop_index('ix_gtc_scenario_connection_ts', table_name='ground_truth_consumption')
    op.drop_table('ground_truth_consumption')
    op.drop_index('ix_gta_scenario_connection', table_name='ground_truth_anomaly')
    op.drop_table('ground_truth_anomaly')
    op.drop_index('uq_assoc_current_per_connection', table_name='connection_association', sqlite_where=sa.text('effective_to IS NULL'), postgresql_where=sa.text('effective_to IS NULL'))
    op.drop_index('ix_assoc_node', table_name='connection_association')
    op.drop_index('ix_assoc_connection', table_name='connection_association')
    op.drop_table('connection_association')
    op.drop_table('synthetic_scenario')
    op.drop_index('ix_network_node_parent', table_name='network_node')
    op.drop_table('network_node')
    op.drop_table('connection')
    # ### end Alembic commands ###


HYPERTABLES = {
    "vending_event": "ts",
    "sensor_reading": "ts",
    "ground_truth_consumption": "ts",
    "ground_truth_technical_loss": "ts",
}


def _promote_hypertables() -> None:
    """TimescaleDB-only: no-op on SQLite. Run after table creation so each
    time-series table is partitioned on its timestamp column from the start.
    """
    bind = op.get_bind()
    if bind.dialect.name != "postgresql":
        return
    op.execute("CREATE EXTENSION IF NOT EXISTS timescaledb")
    for table, time_col in HYPERTABLES.items():
        op.execute(
            f"SELECT create_hypertable('{table}', '{time_col}', "
            "if_not_exists => TRUE, migrate_data => TRUE)"
        )
