/**
 * Data access with two interchangeable sources:
 *
 *  - LIVE  : the FastAPI backend at /api/* (local development; can generate
 *            new scenarios, recompute anything on demand).
 *  - STATIC: a pre-exported JSON snapshot under data/ (the deployed demo).
 *            Vercel runs no Python, so the snapshot is generated by
 *            scripts/export_static_api.py and committed. Same frontend,
 *            same shapes, no server-side execution at request time.
 *
 * Detection: try the live health endpoint once; fall back to static.
 * Static paths flatten query parameters into filenames because static
 * hosting cannot route on a query string.
 */
const DataSource = (() => {
  let mode = null; // 'live' | 'static'

  async function detect() {
    if (mode) return mode;
    try {
      // Probe a real endpoint: live serves JSON, static hosting 404s.
      const res = await fetch('api/scenarios');
      mode = res.ok ? 'live' : 'static';
    } catch {
      mode = 'static';
    }
    return mode;
  }

  function staticPath(kind, parts) {
    const safe = parts.map((p) => String(p).replace(/[^A-Za-z0-9_.-]/g, '_'));
    return `data/${kind}/${safe.join('__')}.json`;
  }

  async function getJSON(url) {
    const res = await fetch(url);
    if (!res.ok) throw new Error(`${url} -> ${res.status}`);
    return res.json();
  }

  // Each method resolves to the same payload shape in either mode.
  const api = {
    async scenarios() {
      return (await detect()) === 'live'
        ? getJSON('api/scenarios')
        : getJSON('data/scenarios.json');
    },
    async root(scenarioId) {
      return (await detect()) === 'live'
        ? getJSON(`api/scenarios/${scenarioId}/root`)
        : getJSON(staticPath('root', [scenarioId]));
    },
    async node(nodeId, scenarioId) {
      return (await detect()) === 'live'
        ? getJSON(`api/nodes/${nodeId}?scenario_id=${scenarioId}`)
        : getJSON(staticPath('node', [nodeId]));
    },
    async nodeTimeseries(nodeId, scenarioId) {
      return (await detect()) === 'live'
        ? getJSON(`api/nodes/${nodeId}/timeseries?scenario_id=${scenarioId}`)
        : getJSON(staticPath('timeseries', [nodeId]));
    },
    async nodeCases(nodeId, scenarioId) {
      return (await detect()) === 'live'
        ? getJSON(`api/nodes/${nodeId}/cases?scenario_id=${scenarioId}`)
        : getJSON(staticPath('cases', [nodeId]));
    },
    async nodeMap(nodeId, scenarioId) {
      return (await detect()) === 'live'
        ? getJSON(`api/nodes/${nodeId}/map?scenario_id=${scenarioId}`)
        : getJSON(staticPath('map', [nodeId]));
    },
    async nodeNonTechnicalLoss(nodeId, scenarioId) {
      return (await detect()) === 'live'
        ? getJSON(`api/nodes/${nodeId}/nontechnical-loss?scenario_id=${scenarioId}`)
        : getJSON(staticPath('ntl', [nodeId]));
    },
    async connectionTimeseries(connectionId, scenarioId) {
      return (await detect()) === 'live'
        ? getJSON(`api/connections/${connectionId}/timeseries?scenario_id=${scenarioId}`)
        : getJSON(staticPath('conn_timeseries', [connectionId]));
    },
    async caseDetail(connectionId, scenarioId) {
      return (await detect()) === 'live'
        ? getJSON(`api/cases/${connectionId}?scenario_id=${scenarioId}`)
        : getJSON(staticPath('case', [connectionId]));
    },
    async caseGroundTruth(connectionId, scenarioId) {
      return (await detect()) === 'live'
        ? getJSON(`api/cases/${connectionId}/ground-truth?scenario_id=${scenarioId}`)
        : getJSON(staticPath('gt', [connectionId]));
    },
    async summary(scenarioId) {
      return (await detect()) === 'live'
        ? getJSON(`api/views/summary?scenario_id=${scenarioId}`)
        : getJSON(staticPath('summary', [scenarioId]));
    },
    async revenueProtection(scenarioId) {
      return (await detect()) === 'live'
        ? getJSON(`api/views/revenue-protection?scenario_id=${scenarioId}`)
        : getJSON(staticPath('revenue', [scenarioId]));
    },
    async heldOutEvaluation() {
      return (await detect()) === 'live'
        ? getJSON('api/module-a/held-out-evaluation')
        : getJSON('data/held_out_evaluation.json');
    },
    async mode() {
      return detect();
    },
  };

  return api;
})();

// Shared app state
const State = {
  scenarioId: null,
  rootId: null,
  summary: null,
  scenarioConfig: null,
};

const CAUSE_COLORS = {
  solar_adoption: '#D97706',
  vacancy: '#64748B',
  meter_failure: '#DC2626',
  full_bypass: '#B91C1C',
  partial_bypass: '#EA580C',
  normal: '#16A34A',
};

function causeBadge(cause) {
  const color = CAUSE_COLORS[cause] || '#475569';
  return `<span class="badge" style="background:${color};color:#fff">${cause}</span>`;
}

function fmtNum(v, digits = 2) {
  if (v === null || v === undefined || Number.isNaN(v)) return '&mdash;';
  return Number(v).toLocaleString(undefined, { minimumFractionDigits: digits, maximumFractionDigits: digits });
}
